name: broline
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.0+1
  flutter_group_sliver:
  carousel_pro: ^1.0.0
  multi_image_picker: ^4.7.15
  splashscreen: ^1.3.5
  firebase_core: ^0.7.0
  provider:
  google_sign_in:
  cloud_firestore:
  pin_code_fields:
  flutter_native_splash:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/broline.jfif
    - assets/images/brolineSplashCroped.jpg
    - assets/images/MainCategory/construction.jpeg
    - assets/images/MainCategory/drug.jpeg
    - assets/images/MainCategory/electronics.jpeg
    - assets/images/MainCategory/entertainment.jpeg
    - assets/images/MainCategory/food.jpeg
    - assets/images/MainCategory/house.jpeg
    - assets/images/MainCategory/jewelery.jpeg
    - assets/images/MainCategory/job.jpeg
    - assets/images/MainCategory/office.jpeg
    - assets/images/MainCategory/other.jpeg
    - assets/images/MainCategory/pets.jpeg
    - assets/images/MainCategory/vehicle.jpeg
    - assets/images/brolineLogo.jpg
    - assets/images/google.png
    - assets/images/MainCategory/carCartoon.jfif
    - assets/images/MainCategory/clothCartoon.jfif
    - assets/images/MainCategory/constructionCartoon.jfif
    - assets/images/MainCategory/electronicsCartoon.jfif
    - assets/images/MainCategory/houseCartoon.jfif
    - assets/images/MainCategory/jobCartoon.jfif
    - assets/images/MainCategory/officeCartoon.jfif
    - assets/images/MainCategory/drugCartoon.jfif
    - assets/images/MainCategory/entertainmentCartoon.jfif
    - assets/images/MainCategory/foodCartoon.png
    - assets/images/MainCategory/petsCartoon.jfif
    - assets/images/rent.jfif
    - assets/images/sell.jfif
    - assets/images/flag.jfif
    - assets/images/houseBackground.jfif
    - assets/images/SubCategory/landCartoon.jfif
    - assets/images/SubCategory/storeCartoon.png
    - assets/images/SubCategory/hallCartoon.jfif
  #   - images/a_dot_ham.jpe    - assets/images/brolineSplashCroped.jpgg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
